# Generated by Django 5.2.6 on 2025-10-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_product_supply_supplyproduct_supply_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage_id',
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.storage'),
        ),
    ]
