# Generated by Django 5.2.6 on 2025-10-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_product_storage_id_product_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='companies.supplier'),
        ),
    ]
