# Generated by Django 5.2.6 on 2025-10-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_supply_supplier_id_supply_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='companies.supplier'),
            preserve_default=False,
        ),
    ]
