# Generated by Django 5.2.6 on 2025-10-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_supply_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.storage'),
            preserve_default=False,
        ),
    ]
